### ISSUE TITLE
Some questions about the code.

### ISSUE THREAD

**Issue by jkdwxm** [QingkaiZeng/GenTaxo#2]
Hi, QingkaiZeng! 
Thanks for offering a brand-new perspective towards Taxonomy Expansion task! I'm trying to learn more about how the Concept Name Generation works. It says the code is implemented based on [TMN](https://github.com/JieyuZ2/TMN) and [GraphWriter-DGL](https://github.com/QipengGuo/GraphWriter-DGL), but I've noticed that the code is the exactly same to [TMN](https://github.com/JieyuZ2/TMN) without any new content or changes. I guess you didn't submit the latest version of the code correctly. LOL.

If you could share the latest version of your code that implements CNG module, it would be very much appreciated. Thanks a lot!

**Comment by mjiang89** [comment]
Hello -  I apologize for recognizing this issue message so late. I wish Qingkai had recognized the issue early and corrected it, OR you two had communicated via emails so you'd got the correct code. No matter if that had happened, I am urging the leading author Qingkai to pay attention to this issue - update the code and documentation, etc. If you have any questions, please feel free to send a message to all the authors of the paper, including me (mjiang2@nd.edu).

Best,
Meng

**Comment by QingkaiZeng** [comment]
Sorry for the late update, jkdwxm. Compared with the original GenTaxo, I made several changes to achieve stable and better performance. If you have any questions, feel free to let me know.

**Comment by QingkaiZeng** [comment]
FYI, my email address is qzeng@nd.edu.
